# PyTorch Tutorial For Beginners: All the Basics

https://learnopencv.com/pytorch-for-beginners-basics/

In [1]:
import torch

a = torch.ones(5)
print(a)

b = torch.zeros(5)
print(b)


tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])


In [2]:
c = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
print(c)

tensor([1., 2., 3., 4., 5.])


In [6]:
d = torch.zeros(3,2)
print(d)

e = torch.ones(3,2)
print(e)

f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(f)

g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(g)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [7]:
print(f.shape)
# torch.Size([2, 2])
 
print(e.shape)
# torch.Size([3, 2])
 
print(g.shape)
# torch.Size([2, 2, 2])

torch.Size([2, 2])
torch.Size([3, 2])
torch.Size([2, 2, 2])


In [8]:
# Get element at index 2
print(c[2])
 
# tensor(3.)

tensor(3.)


In [9]:
# All indices starting from 0
 
# Get element at row 1, column 0
print(f[1,0])
# We can also use the following
print(f[1][0])
 
# tensor(3.)
 
# Similarly for 3D Tensor
print(g[1,0,0])
print(g[1][0][0])
 
# tensor(5.)

tensor(3.)
tensor(3.)
tensor(5.)
tensor(5.)


In [10]:
# All elements
print(f[:])
 
# All elements from index 1 to 2 (inclusive)
print(c[1:3])
 
# All elements till index 4 (exclusive)
print(c[:4])
 
# First row
print(f[0,:])
 
# Second column
print(f[:,1])

tensor([[1., 2.],
        [3., 4.]])
tensor([2., 3.])
tensor([1., 2., 3., 4.])
tensor([1., 2.])
tensor([2., 4.])


In [11]:
int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)
 
# torch.int64
 
# What if we changed any one element to floating point number?
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)
 
# torch.float32
 
print(int_tensor)
 
# tensor([[1., 2., 3.],
#        [4., 5., 6.]])
 
 
# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype=torch.int32)
print(int_tensor.dtype)
 
# torch.int32
print(int_tensor)
 
# tensor([[1, 2, 3],
#        [4, 5, 6]], dtype=torch.int32)

torch.int64
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [12]:
# Import NumPy
import numpy as np
 
# Tensor to Array
f_numpy = f.numpy()
print(f_numpy)
 
# array([[1., 2.],
#       [3., 4.]], dtype=float32)
 
# Array to Tensor
h = np.array([[8,7,6,5],[4,3,2,1]])
h_tensor = torch.from_numpy(h)
print(h_tensor)
 
# tensor([[8, 7, 6, 5],
#        [4, 3, 2, 1]])

[[1. 2.]
 [3. 4.]]
tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


In [13]:
# Create tensor
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])
 
# Addition
print(tensor1+tensor2)
# We can also use
print(torch.add(tensor1,tensor2))
 
# tensor([[ 0,  4,  0],
#        [ 8,  0, 12]])
 
# Subtraction
print(tensor1-tensor2)
# We can also use
print(torch.sub(tensor1,tensor2))
 
# tensor([[ 2,  0,  6],
#        [ 0, 10,  0]])
 
# Multiplication
# Tensor with Scalar
print(tensor1 * 2)
# tensor([[ 2,  4,  6],
#        [ 8, 10, 12]])
 
# Tensor with another tensor
# Elementwise Multiplication
print(tensor1 * tensor2)
# tensor([[ -1,   4,  -9],
#        [ 16, -25,  36]])
 
# Matrix multiplication
tensor3 = torch.tensor([[1,2],[3,4],[5,6]])
print(torch.mm(tensor1,tensor3))
# tensor([[22, 28],
#        [49, 64]])
 
# Division
# Tensor with scalar
print(tensor1/2)
# tensor([[0, 1, 1],
#        [2, 2, 3]])
 
# Tensor with another tensor
# Elementwise division
print(tensor1/tensor2)
# tensor([[-1,  1, -1],
#        [ 1, -1,  1]])

tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[ -1,   4,  -9],
        [ 16, -25,  36]])
tensor([[22, 28],
        [49, 64]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[-1.,  1., -1.],
        [ 1., -1.,  1.]])


In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

# Move a tensor to the Mac GPU
x = torch.ones(5, device=device)
print(x)

Using device: mps
tensor([1., 1., 1., 1., 1.], device='mps:0')


In [ ]:
# Check if CUDA is available, otherwise default to CPU
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

Using device: mps


In [23]:
# Create a tensor for CPU
# This will occupy CPU RAM
tensor_cpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cpu')
 
# Create a tensor for GPU
# This will occupy GPU RAM
tensor_gpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='mps')


In [22]:
# This uses CPU RAM
tensor_cpu = tensor_cpu * 5
 
# This uses GPU RAM
# Focus on GPU RAM Consumption
tensor_gpu = tensor_gpu * 5